before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra

script:
- mkdir _build
- cd ./tex
- pdflatex -output-directory ../_build ./00_main.tex
- mv ../_build/00_main.pdf ../_build/lecture_notes.pdf
- cd ..
